<input type="hidden" id="level" name="level" value="2">
  <div class="col-md-4">

  <label>Official mail ID (Generated by HO)</label>
<select class="form-control status" name="official_mail" id="official_mail">
<option value="">--Select--</option>
<option value="Yes">Yes</option>
<option value="No">No</option>
</select>
<span id="error_official_mail" class="text-danger"></span>
<div class="status_remarks">
<label>mail ID</label>
<input type="text" name="official_mail_id" id="official_mail_id" class="form-control" >
<span id="error_official_mail_id" class="text-danger"></span>
</div>


</div>
<!---->
  <div class="col-md-4">

  <label>Google Listing</label>
<select class="form-control status" name="google_listing" id="google_listing">
<option value="">--Select--</option>
<option value="Yes">Yes</option>
<option value="No">No</option>
</select>
<span id="error_google_listing" class="text-danger"></span>
<div class="status_remarks">
<label>Enter Link</label>
<input type="text" name="google_link" id="google_link" class="form-control" >
<span id="error_google_link" class="text-danger"></span>
</div>


</div>
<!---->
  <div class="col-md-4">

  <label>FB Page</label>
<select class="form-control status" name="fbpage" id="fbpage">
<option value="">--Select--</option>
<option value="Yes">Yes</option>
<option value="No">No</option>
</select>
<span id="error_fbpage" class="text-danger"></span>
<div class="status_remarks">

<label>Enter Link</label>
<input type="text" name="fblink" id="fblink" class="form-control" >
<span id="error_fblink" class="text-danger"></span>
</div>


</div>
<!---->
  <div class="col-md-4">

  <label>Insta Page</label>
<select class="form-control status" name="instapage" id="instapage">
<option value="">--Select--</option>
<option value="Yes">Yes</option>
<option value="No">No</option>
</select>
<span id="error_instapage" class="text-danger"></span>
<div class="status_remarks">
<label>Link</label>
<input type="text" name="instalink" id="instalink" class="form-control" >
<span id="error_instalink" class="text-danger"></span>
</div>


</div>
<!---->
  <div class="col-md-4">

  <label>Menu Dine-In</label>
<select class="form-control status" name="menu_dine_in" id="menu_dine_in">
<option value="">--Select--</option>
<option value="Yes">Yes</option>
<option value="No">No</option>
</select>
<span id="error_menu_dine_in" class="text-danger"></span>
<div class="status_remarks">
<label>Upload</label>
<input type="file" name="menu_dine_in_doc[]" id="menu_dine_in_doc" class="form-control" multiple >
<span id="error_menu_dine_in_doc" class="text-danger"></span>
</div>


</div>
<!---->
  <div class="col-md-4">

  <label>Menu Online</label>
<select class="form-control status" name="menu_online" id="menu_online">
<option value="">--Select--</option>
<option value="Yes">Yes</option>
<option value="No">No</option>
</select>
<span id="error_menu_online" class="text-danger"></span>
<!-- <div class="status_remarks">
<label>Enter Detail</label>
<input type="text" name="menu_link" id="menu_link" class="form-control" >
<span id="error_menu_link" class="text-danger"></span>
</div> -->

<div class="status_remarks">
<label>Upload</label>
<input type="file" name="menu_online_doc[]" id="menu_online_doc" class="form-control" multiple >
<span id="error_menu_online_doc" class="text-danger"></span>
</div>


</div>

<!---->
  <div class="col-md-4">

  <label>Coming Soon Banner</label>
<select class="form-control status" name="coming_soon_banner_status" id="coming_soon_banner_status">
<option value="">--Select--</option>
<option value="Yes">Yes</option>
<option value="No">No</option>
</select>
<span id="error_coming_soon_banner_status" class="text-danger"></span>
<div class="status_remarks">
<label>Coming Soon Banner Layout</label>
<input type="file" name="coming_soon_banner[]" id="coming_soon_banner" class="form-control" multiple>
<span id="error_coming_soon_banner" class="text-danger"></span>
</div>


</div>
<!---->
 <div class="col-md-4">

  <label>NPI Pamphlets</label>
<select class="form-control status" name="npi" id="npi">
<option value="">--Select--</option>
<option value="Yes">Yes</option>
<option value="No">No</option>
</select>
<span id="error_npi" class="text-danger"></span>
<div class="status_remarks">
<label>Pamphlets Layout</label>
<input type="file" name="npi_template[]" id="npi_template" class="form-control" multiple>
<span id="error_npi_template" class="text-danger"></span>
</div>


</div>
<!---->
  <div class="col-md-4">

  <label>Hoarding design</label>
<select class="form-control status" name="hoarding" id="hoarding">
<option value="">--Select--</option>
<option value="Yes">Yes</option>
<option value="No">No</option>
</select>
<span id="error_hoarding" class="text-danger"></span>
<div class="status_remarks">
<label>Doc</label>
<input type="file" name="hoarding_design[]" id="hoarding_design" class="form-control" multiple>
<span id="error_hoarding_design" class="text-danger"></span>
</div>


</div>
<!---->
  <div class="col-md-4">

  <label>Banner design</label>
<select class="form-control status" name="banner" id="banner">
<option value="">--Select--</option>
<option value="Yes">Yes</option>
<option value="No">No</option>
</select>
<span id="error_banner" class="text-danger"></span>
<div class="status_remarks">
<label>Doc</label>
<input type="file" name="banner_doc[]" id="banner_doc" class="form-control" multiple>
<span id="error_banner_doc" class="text-danger"></span>
</div>


</div>
<!---->
 
  <div class="col-md-4">

  <label>Foodshots</label>
<select class="form-control status" name="foodshots" id="foodshots">
<option value="">--Select--</option>
<option value="Yes">Yes</option>
<option value="No">No</option>
</select>
<span id="error_foodshots" class="text-danger"></span>
<div class="status_remarks">
<label>Doc</label>
<input type="file" name="foodshots_doc[]" id="foodshots_doc" class="form-control" multiple>
<span id="error_foodshots_doc" class="text-danger"></span>
</div>


</div>
 <div class="col-md-4">

  <label>Other Marketing Activity</label>
<select class="form-control status" name="newspaper" id="newspaper">
<option value="">--Select--</option>
<option value="Yes">Yes</option>
<option value="No">No</option>
</select>
<span id="error_newspaper" class="text-danger"></span>
<div class="status_remarks">
<label>Doc</label>
<input type="file" name="newspaper_ad[]" id="newspaper_ad" class="form-control" multiple>
<span id="error_newspaper_ad" class="text-danger"></span>
</div>


</div>
<!---->