<input type="hidden" id="level" name="level" value="2">
  <div class="col-md-4">

  <label class="required">Official mail ID (Generated by HO)</label>
<select class="form-control status" name="official_mail" id="official_mail">
<option value="">--Select--</option>
<option value="Yes" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->official_mail!='' && $fanchise_pre_launch_data->official_mail=='Yes') selected  @endif>Yes</option>
<option value="No" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->official_mail!='' && $fanchise_pre_launch_data->official_mail=='No') selected  @endif>No</option>
</select>
<span id="error_official_mail" class="text-danger"></span>
<div class="status_remarks" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->official_mail!='' && $fanchise_pre_launch_data->official_mail=='Yes') style='display:block'  @endif>
<label>mail ID</label>
<input type="text" name="official_mail_id" id="official_mail_id" class="form-control" value="{{$fanchise_pre_launch_data->official_mail_id}}">
<span id="error_official_mail_id" class="text-danger"></span>
</div>


</div>
<!---->
  <div class="col-md-4">

  <label class="required">Google Listing</label>
<select class="form-control status" name="google_listing" id="google_listing">
<option value="">--Select--</option>
<option value="Yes" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->google_listing!='' && $fanchise_pre_launch_data->google_listing=='Yes') selected  @endif>Yes</option>
<option value="No" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->google_listing!='' && $fanchise_pre_launch_data->google_listing=='No') selected  @endif>No</option>
</select>
<span id="error_google_listing" class="text-danger"></span>
<div class="status_remarks"  @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->google_listing!='' && $fanchise_pre_launch_data->google_listing=='Yes') style='display:block'  @endif>
<label>Enter Link</label>
<input type="text" name="google_link" id="google_link" class="form-control" value="{{$fanchise_pre_launch_data->google_link}}">
<span id="error_google_link" class="text-danger"></span>
</div>


</div>
<!---->
  <div class="col-md-4">

  <label class="required">FB Page</label>
<select class="form-control status" name="fbpage" id="fbpage">
<option value="">--Select--</option>
<option value="Yes" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->fbpage!='' && $fanchise_pre_launch_data->fbpage=='Yes') selected  @endif>Yes</option>
<option value="No" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->fbpage!='' && $fanchise_pre_launch_data->fbpage=='No') selected  @endif>No</option>
</select>
<span id="error_fbpage" class="text-danger"></span>
<div class="status_remarks" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->fbpage!='' && $fanchise_pre_launch_data->fbpage=='Yes') style='display:block'  @endif>

<label>Enter Link</label>
<input type="text" name="fblink" id="fblink" class="form-control" value="{{$fanchise_pre_launch_data->fblink}}">
<span id="error_fblink" class="text-danger"></span>
</div>


</div>
<!---->
  <div class="col-md-4">

  <label class="required">Insta Page</label>
<select class="form-control status" name="instapage" id="instapage">
<option value="">--Select--</option>
<option value="Yes" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->instapage!='' && $fanchise_pre_launch_data->instapage=='Yes') selected  @endif>Yes</option>
<option value="No" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->instapage!='' && $fanchise_pre_launch_data->instapage=='No') selected  @endif>No</option>
</select>
<span id="error_instapage" class="text-danger"></span>
<div class="status_remarks" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->instapage!='' && $fanchise_pre_launch_data->instapage=='Yes') style='display:block'  @endif>
<label>Link</label>
<input type="text" name="instalink" id="instalink" class="form-control" value="{{$fanchise_pre_launch_data->instalink}}">
<span id="error_instalink" class="text-danger"></span>
</div>


</div>
<!---->
  <div class="col-md-4">

  <label class="required">Menu Dine-In</label>
<select class="form-control status" name="menu_dine_in" id="menu_dine_in">
<option value="">--Select--</option>
<option value="Yes" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->menu_dine_in!='' && $fanchise_pre_launch_data->menu_dine_in=='Yes') selected  @endif>Yes</option>
<option value="No" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->menu_dine_in!='' && $fanchise_pre_launch_data->menu_dine_in=='No') selected  @endif>No</option>
</select>
<span id="error_menu_dine_in" class="text-danger"></span>
<div class="status_remarks" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->menu_dine_in!='' && $fanchise_pre_launch_data->menu_dine_in=='Yes') style='display:block'  @endif>
<label>Upload</label>
<?php 
$docs=DB::table('pre_launch_docs')->where([['fanchise_id','=',$fanchise_detail->id],['doc_name','=','menu_dine_in_doc']])->get();
$a=1;
?>

@foreach($docs as $doc)
<a href="{{url('public/uploads/fanchise_doc/'.$doc->doc)}}"  target="_blank" style="color: blue;">View{{$a++}}</a>
@endforeach

<input type="file" name="menu_dine_in_doc[]" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->menu_dine_in!='' && $fanchise_pre_launch_data->menu_dine_in=='Yes') @else id="menu_dine_in_doc"  @endif  class="form-control" multiple >
<span id="error_menu_dine_in_doc" class="text-danger"></span>
</div>


</div>
<!---->
  <div class="col-md-4">

  <label class="required">Menu Online</label>
<select class="form-control status" name="menu_online" id="menu_online">
<option value="">--Select--</option>
<option value="Yes" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->menu_online!='' && $fanchise_pre_launch_data->menu_online=='Yes') selected  @endif>Yes</option>
<option value="No" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->menu_online!='' && $fanchise_pre_launch_data->menu_online=='No') selected  @endif>No</option>
</select>
<span id="error_menu_online" class="text-danger"></span>
<!-- <div class="status_remarks" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->menu_online!='' && $fanchise_pre_launch_data->menu_online=='Yes') style='display:block'  @endif>
<label>Enter Detail</label>
<input type="text" name="menu_link" id="menu_link" class="form-control" value="{{$fanchise_pre_launch_data->menu_link}}">
<span id="error_menu_link" class="text-danger"></span>
</div> -->

<div class="status_remarks" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->menu_online!='' && $fanchise_pre_launch_data->menu_online=='Yes') style='display:block'  @endif>
<label>Upload</label>
<?php 
$docs=DB::table('pre_launch_docs')->where([['fanchise_id','=',$fanchise_detail->id],['doc_name','=','menu_online_doc']])->get();
$a=1;
?>

@foreach($docs as $doc)
<a href="{{url('public/uploads/fanchise_doc/'.$doc->doc)}}"  target="_blank" style="color: blue;">View{{$a++}}</a>
@endforeach
<input type="file" name="menu_online_doc[]"  @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->menu_online!='' && $fanchise_pre_launch_data->menu_online=='Yes') @else id="menu_online_doc"  @endif  class="form-control" multiple >
<span id="error_menu_online_doc" class="text-danger"></span>
</div>



</div>

<!---->
  <div class="col-md-4">

  <label class="required">Coming Soon Banner</label>
<select class="form-control status" name="coming_soon_banner_status" id="coming_soon_banner_status">
<option value="">--Select--</option>
<option value="Yes" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->coming_soon_banner_status!='' && $fanchise_pre_launch_data->coming_soon_banner_status=='Yes') selected  @endif>Yes</option>
<option value="No" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->coming_soon_banner_status!='' && $fanchise_pre_launch_data->coming_soon_banner_status=='No') selected  @endif>No</option>
</select>
<span id="error_coming_soon_banner_status" class="text-danger"></span>
<div class="status_remarks" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->coming_soon_banner_status!='' && $fanchise_pre_launch_data->coming_soon_banner_status=='Yes') style='display:block'  @endif>
<label>Coming Soon Banner Layout</label>
<?php 
$docs=DB::table('pre_launch_docs')->where([['fanchise_id','=',$fanchise_detail->id],['doc_name','=','coming_soon_banner']])->get();
$a=1;
?>

@foreach($docs as $doc)
<a href="{{url('public/uploads/fanchise_doc/'.$doc->doc)}}"  target="_blank" style="color: blue;">View{{$a++}}</a>
@endforeach

<input type="file" name="coming_soon_banner[]" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->coming_soon_banner_status!='' && $fanchise_pre_launch_data->coming_soon_banner_status=='Yes') @else id="coming_soon_banner"  @endif  class="form-control" multiple>
<span id="error_coming_soon_banner" class="text-danger"></span>
</div>


</div>
<!---->
  <div class="col-md-4">

  <label class="required">NPI Pamphlets</label>
<select class="form-control status" name="npi" id="npi">
<option value="">--Select--</option>
<option value="Yes" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->npi!='' && $fanchise_pre_launch_data->npi=='Yes') selected  @endif>Yes</option>
<option value="No" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->npi!='' && $fanchise_pre_launch_data->npi=='No') selected  @endif>No</option>
</select>
<span id="error_npi" class="text-danger"></span>
<div class="status_remarks" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->npi!='' && $fanchise_pre_launch_data->npi=='Yes') style='display:block'  @endif>
<label>Pamphlets Layout</label>
<?php 
$docs=DB::table('pre_launch_docs')->where([['fanchise_id','=',$fanchise_detail->id],['doc_name','=','npi_template']])->get();
$a=1;
?>

@foreach($docs as $doc)
<a href="{{url('public/uploads/fanchise_doc/'.$doc->doc)}}"  target="_blank" style="color: blue;">View{{$a++}}</a>
@endforeach
<input type="file"  @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->npi!='' && $fanchise_pre_launch_data->npi=='Yes') @else id="npi_template"  @endif  name="npi_template[]"  class="form-control" multiple>
<span id="error_npi_template" class="text-danger"></span>
</div>


</div>
<!---->
  <div class="col-md-4">

  <label class="required">Hoarding design</label>
<select class="form-control status" name="hoarding" id="hoarding">
<option value="">--Select--</option>
<option value="Yes" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->hoarding!='' && $fanchise_pre_launch_data->hoarding=='Yes') selected  @endif>Yes</option>
<option value="No" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->hoarding!='' && $fanchise_pre_launch_data->hoarding=='No') selected  @endif>No</option>
</select>
<span id="error_hoarding" class="text-danger"></span>
<div class="status_remarks" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->hoarding!='' && $fanchise_pre_launch_data->hoarding=='Yes') style='display:block'  @endif>
<label>Doc</label>
<?php 
$docs=DB::table('pre_launch_docs')->where([['fanchise_id','=',$fanchise_detail->id],['doc_name','=','hoarding_design']])->get();
$a=1;
?>

@foreach($docs as $doc)
<a href="{{url('public/uploads/fanchise_doc/'.$doc->doc)}}"  target="_blank" style="color: blue;">View{{$a++}}</a>
@endforeach
<input type="file" name="hoarding_design[]"  @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->hoarding!='' && $fanchise_pre_launch_data->hoarding=='Yes') @else id="hoarding_design"  @endif  class="form-control" multiple>
<span id="error_hoarding_design" class="text-danger"></span>
</div>


</div>
<!---->
  <div class="col-md-4">

  <label class="required">Banner design</label>
<select class="form-control status" name="banner" id="banner">
<option value="">--Select--</option>
<option value="Yes" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->banner!='' && $fanchise_pre_launch_data->banner=='Yes') selected  @endif>Yes</option>
<option value="No" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->banner!='' && $fanchise_pre_launch_data->banner=='No') selected  @endif>No</option>
</select>
<span id="error_banner" class="text-danger"></span>
<div class="status_remarks" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->banner!='' && $fanchise_pre_launch_data->banner=='Yes') style='display:block'  @endif>
<label>Doc</label>
<?php 
$docs=DB::table('pre_launch_docs')->where([['fanchise_id','=',$fanchise_detail->id],['doc_name','=','banner_doc']])->get();
$a=1;
?>

@foreach($docs as $doc)
<a href="{{url('public/uploads/fanchise_doc/'.$doc->doc)}}"  target="_blank" style="color: blue;">View{{$a++}}</a>
@endforeach
<input type="file" name="banner_doc[]"  @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->banner!='' && $fanchise_pre_launch_data->banner=='Yes') @else id="banner_doc"  @endif class="form-control" multiple>
<span id="error_banner_doc" class="text-danger"></span>
</div>


</div>
<!---->
  <div class="col-md-4">

  <label class="required">Other Marketing Activity</label>
<select class="form-control status" name="newspaper" id="newspaper">
<option value="">--Select--</option>
<option value="Yes" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->newspaper!='' && $fanchise_pre_launch_data->newspaper=='Yes') selected  @endif>Yes</option>
<option value="No" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->newspaper!='' && $fanchise_pre_launch_data->newspaper=='No') selected  @endif>No</option>
</select>
<span id="error_newspaper" class="text-danger"></span>
<div class="status_remarks" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->newspaper!='' && $fanchise_pre_launch_data->newspaper=='Yes') style='display:block'  @endif>
<label>Doc</label>
<?php 
$docs=DB::table('pre_launch_docs')->where([['fanchise_id','=',$fanchise_detail->id],['doc_name','=','newspaper_ad']])->get();
$a=1;
?>

@foreach($docs as $doc)
<a href="{{url('public/uploads/fanchise_doc/'.$doc->doc)}}"  target="_blank" style="color: blue;">View{{$a++}}</a>
@endforeach
<input type="file" name="newspaper_ad[]"  @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->newspaper!='' && $fanchise_pre_launch_data->newspaper=='Yes') @else id="newspaper_ad"  @endif class="form-control" multiple>
<span id="error_newspaper_ad" class="text-danger"></span>
</div>


</div>
<!---->
  <div class="col-md-4">

  <label class="required">Foodshots</label>
<select class="form-control status" name="foodshots" id="foodshots">
<option value="">--Select--</option>
<option value="Yes" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->foodshots!='' && $fanchise_pre_launch_data->foodshots=='Yes') selected  @endif>Yes</option>
<option value="No" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->foodshots!='' && $fanchise_pre_launch_data->foodshots=='No') selected  @endif>No</option>
</select>
<span id="error_foodshots" class="text-danger"></span>
<div class="status_remarks" @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->foodshots!='' && $fanchise_pre_launch_data->foodshots=='Yes') style='display:block'  @endif>
<label>Doc</label>
<?php 
$docs=DB::table('pre_launch_docs')->where([['fanchise_id','=',$fanchise_detail->id],['doc_name','=','foodshots_doc']])->get();
$a=1;
?>

@foreach($docs as $doc)
<a href="{{url('public/uploads/fanchise_doc/'.$doc->doc)}}"  target="_blank" style="color: blue;">View{{$a++}}</a>
@endforeach
<input type="file" name="foodshots_doc[]"  @if($fanchise_pre_launch_data!='' && $fanchise_pre_launch_data->foodshots!='' && $fanchise_pre_launch_data->foodshots=='Yes') @else id="foodshots_doc"  @endif class="form-control" multiple>
<span id="error_foodshots_doc" class="text-danger"></span>
</div>


</div>